<?php

/**
 * @file
 * The content management module.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function content_management_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'content_management') {
    // Attach extra css.
    $view->element['#attached']['library'][] = 'content_management/style';

    // Build an easy to access content type array with human readable name.
    $contentTypes = \Drupal::service('entity.manager')
      ->getStorage('node_type')
      ->loadMultiple();
    $cts = [];
    foreach ($contentTypes as $ct) {
      $cts[$ct->id()] = $ct->label();
    }

    // Get the view parameter.
    $arg = array_shift($view->args);

    if (is_string($arg) && isset($cts[$arg])) {
      $view->setTitle(t('Manage @ct content', ['@ct' => t($cts[$arg])]));
    }
    else {
      $view->setTitle(t('Error generating content management.'));
      $view->empty['area']->options['content']['value'] = t("The content type you tried to reference doesn't exist. Please make sure it exists in the database.");
    }
  }
}
